### ISSUE TITLE
arrow-declare test ES5 version not equivalent to ES6

### ISSUE THREAD

**Issue by epidemian** [kpdecker/six-speed#39] opened 2016-03-02 04:46 UTC
The ES6 version declares `obj` as:

``` javascript
var obj = {
  value: 42,
  fn: function() {
    return () => this.value;
  }
};
```

While the ES5 version declares it as:

``` javascript
var obj = {
  value: 42,
  fn: function() {
    return function() {
      return obj.value;
    };
  }
};
```

Then it is asserted that `obj.fn()()` returns `42` for both cases.

However, in the ES5 version `obj.fn` returns a function that _always_ returns the value of `obj.value`, while the ES6 is quite more dynamic, in that the return value depends on the object over which `obj.fn` is invoked:

``` javascript
var obj2 = {value: ":)", fn: obj.fn}
obj2.fn()() // returns 42 on ES5 test, but ":)" on ES6 test

// Or, more succinctly:
obj.fn.call({value: ":)"})() // 42 on ES5 test, but ":)" on ES6 test
```

I'd propose to change the ES5 version of `obj` to either:

``` javascript
var obj = {
  value: 42,
  fn: function() {
    var self = this;
    return function() {
      return self.value;
    };
  }
};
```

(This is basically what [Babel does](https://babeljs.io/repl/#?experimental=true&evaluate=true&loose=false&spec=false&code=var%20obj%20%3D%20{%0A%20%20value%3A%2042%2C%0A%20%20fn%3A%20function%28%29%20{%0A%20%20%20%20return%20%28%29%20%3D%3E%20this.value%3B%0A%20%20}%0A}%3B))

Or:

``` javascript
var obj = {
  value: 42,
  fn: function() {
    return function() {
      return this.value;
    }.bind(this);
  }
};
```

So that the ES5 and ES6 behaviour is better aligned :smile_cat: 

I'm not sure if this will make a noticeable difference on the test runs (i don't have time now to set up all the environment to run them), but i suspect it will :)

**Comment by kpdecker** [comment] 2016-03-05 16:49
Dupe of #36

**Closed as completed by kpdecker** 2016-03-05 16:49 UTC
